# Generated by Django 4.2.7 on 2023-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_s',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
